services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: stock_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Automatic SQL initialization (commented out for manual control)
      # - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  airflow:
    image: apache/airflow:3.0.4-python3.12
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/stock_data
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    ports:
      - "8080:8080"
    volumes:
      - ./stock_etl/airflow_dags:/opt/airflow/dags
      - ./stock_etl:/opt/airflow/stock_etl
      - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "
        pip install holidays psycopg2-binary &&
        airflow standalone
      "

volumes:
  postgres_data:
  airflow_logs:
  pgadmin_data: